name: Delete Artifacts

on:
  schedule:
    - cron: '0 4 * * *' # every day at 4 AM UTC

jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          expire-in: 30days # Setting this value to 0 will delete all artifacts