name: .NET

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: [ '8.0.x' ]
        build-configuration: [ 'Release' ]

    steps:
    - name: Checkout Branch
      uses: actions/checkout@v3
    
    - name: Setup .NET ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Restore Dependencies
      run: dotnet restore --nologo --verbosity=minimal --force

    - name: Build Solution
      run: dotnet build --nologo --verbosity=minimal --no-restore --configuration ${{ matrix.build-configuration }}

    - name: Test Solution
      run: dotnet test --nologo --verbosity=minimal --no-restore --no-build --configuration ${{ matrix.build-configuration }}
